print(4+3)
print(4-3)
print(4*3)
print(4%3)
print(4/3)
print(4**3)
print(4//3)

print('vale')
print('rodriguez')
print('mexico')
print('im enjoying 30 days of python')
 
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type({'vale', 'phyton','Mexico'}))
print(type('vale'))
print(type('rodriguez'))
print(type('mexico'))